### ISSUE TITLE
Drop talk length text field for dropdown

### ISSUE THREAD

**Issue by adamwathan** [tighten/symposium#113]
Right now, the "talk length" field when creating a new talk is a free form text field meant to be entered in minutes.

This is kinda crappy for workshops that are usually 3+ hours, and gives too much flexibility for shorter talks.

What do you think of a dropdown with the following options?
- 15 min
- 30 min
- 45 min
- 60 min
- Half day
- Full day

**Comment by mattstauffer** [comment]
I like it but i think some lightning are shorter?

Here's what we got from our current db:
-5 (someone screwing around)
15 (lightning)
15 (lightning)
15 (lightning)
15 (lightning)
15 (lightning)
20 (lightning)
20 (lightning)
25 (someone screwing around)
30
30
30
33 (fake)
35 (fake)
about a dozen `40`
several dozen `45`
several dozen `50`
several dozen `60`
half dozen `120`
150
180
180
360
1578901

So really what we're missing is the 2 hour and 3 hour options. I bet the `50` minute ones wouldn't be too angry if they were crammed into `45` or `60`?

**Comment by adamwathan** [comment]
Yeah I mean you can give a 50 minute talk in both a 45 or 60 minute conference slot, doesn't really matter.

I think 2 hours is probably reasonable to add, 3 hours though would just be the "half day" option. A full day workshop is only really 5.5 hours even, based on the breaks we had at Laracon EU.

Could even make it contextual:

- Lightning: No time field at all, just assume its a 5-15 minute thing, precision isn't really important for these
- Seminar: 30/45/60min? Maybe there's normal conference talks that are longer?
- Workshop: Half day or full day, maybe there's shorter ones that are short enough to be in hours? Never seen one shorter than 3 hours which is def. half day.

**Comment by mattstauffer** [comment]
Huh, that makes a ton of sense. Who cares about length on lightning, for sure. And who's gonna give a 3-hour seminar?

Great thinking. I like that a lot.

**Comment by andrewmile** [comment]
Closing this since a `type` field has been added since this issue was created.
