### ISSUE TITLE
Support full range of Unicode.

### ISSUE THREAD

**Issue by heiglandreas** [tighten/symposium#176]
Currently it is not possible to add certain Unicode-Characters like PILE_OF_POO (💩). Neither in the title of a talk, not in the talk-description.

I noticed that when I tried to add a talk about exactly that subject that should have the Emoji in the title ;)

**Comment by mattstauffer** [comment]
:+1: 💩

**Comment by heiglandreas** [comment]
It **is** possible to add the character using the corresponding HTML-Entity (f.e. ```&#x1f4a9;```) but that causes the character to be displayed on the next edit and then it is gone on saving.... 😢 

Might that be an issue with the storage-backend (MySQL with UTF8 instead of UTF8mb4)?

**Comment by mattstauffer** [comment]
Not sure exactly how I'm going to structure the code, but I just did it locally, and it requires:

- update `config/database.php` encoding and collation to `utf8mb4`  and `utf8mb4_general_ci`.
- update database, table, and all columns' encoding to `utf8mb4` and encoding `utf8mb4_general_ci`.

Once you do that, it works:

![image](https://cloud.githubusercontent.com/assets/151829/16363952/64e22ac2-3ba8-11e6-819a-d8f376298ad8.png)

**Comment by mattstauffer** [comment]
working here: https://github.com/tightenco/symposium/tree/emoji-support

**Comment by andrewmile** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add emoji support](https://trello.com/c/JN7xXGyc/96-add-emoji-support)
