### ISSUE TITLE
Normalize conference rules between create form and update controller action

### ISSUE THREAD

**Issue by mattstauffer** [tighten/symposium#195]

**Comment by rossjcooper** [comment]
Hi @mattstauffer,
I am currently looking at this, starting by moving the validation step into the controller store() function, but as I can see from the tests the validation is tested on the CreateConferenceForm class. Is there a reason for this or should these tests now cover testing the controller instead through a mocked form submission?

**Comment by mattstauffer** [comment]
Hey @rossjcooper, I think we were originally intending to use those form objects everywhere, but didn't, so now that one is just separated strangely.

Maybe I'm wrong, though? But yah, if only one action in the whole site is separated out into a form object, I would just say let's drop it and its tests and move it into the controller and normal integration tests.

**Comment by andrewmile** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Normalize conference rules between create form and update controller action](https://trello.com/c/gtJbELfC/87-normalize-conference-rules-between-create-form-and-update-controller-action)
