### ISSUE TITLE
Add speaker-specific metadata about conferences

### ISSUE THREAD

**Issue by mattstauffer** [tighten/symposium#204]
https://twitter.com/TheLarkInn/status/821945642503307264

It'd be nice to be able to allow speakers to track more information about conferences they're speaking at all together in one place.

**Comment by greydnls** [comment]
@mattstauffer do you think adding the concept of `Acceptances` to abstracts would allow speakers to track (and optionally expose) where an abstract has been accepted. Assuming the conference is also on the platform they could link it, and then easily add notes about travel, etc.

**Comment by greydnls** [comment]
Mind if I take a stab at it?

**Comment by mattstauffer** [comment]
I wouldn't mind at all!

**Comment by andrewmile** [comment]
Closed by #413
