### ISSUE TITLE
Track popularity and lifecycle of a talk

### ISSUE THREAD

**Issue by mattstauffer** [tighten/symposium#25]
Thanks to @mathiasverraes

Use Joind.in and  Lanyrd and Meetup.com information, reviews, etc.

**Comment by mattstauffer** [comment]
This issue was moved to tightenco/symposium#25

**Comment by elazar** [comment]
Seems to have some overlap with #99.

**Comment by mattstauffer** [comment]
Requires #17 so that we can know when a talk was given vs. just applied; benefits from #99 but doesn't require it.

**Comment by andrewmile** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Track popularity and lifecycle of a talk](https://trello.com/c/ul9qOF1o/72-track-popularity-and-lifecycle-of-a-talk)

**Comment by andrewmile** [comment]
Completed by #392
