### ISSUE TITLE
Track speaker package for conferences

### ISSUE THREAD

**Issue by mattstauffer** [tighten/symposium#26]
Thanks @mathiasverraes
- covers travel cost
- travel cost max costs
- covers hotel
- covers food
- other stuff?

**Comment by mattstauffer** [comment]
This issue was moved to tightenco/symposium#26

**Comment by andrewmile** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Track speaker package for conferences](https://trello.com/c/m5hyRUgQ/91-track-speaker-package-for-conferences)

**Comment by andrewmile** [comment]
Closed by #413
