### ISSUE TITLE
Add option for no CFP.

### ISSUE THREAD

**Issue by brandonsavage** [tighten/symposium#27]
Some conferences do personal invites or don't run a standard call for papers (SOLIDay is one). It would be great to have an option for no CFP.

**Comment by mattstauffer** [comment]
This issue was moved to tightenco/symposium#27

**Comment by andrewmile** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add option for no CFP](https://trello.com/c/d6sObgeI/90-add-option-for-no-cfp)
