### ISSUE TITLE
Create a "submit to conference" button

### ISSUE THREAD

**Issue by mattstauffer** [tighten/symposium#29]
Connected to #12, not only allowing users to mark a specific talk as "sent to" a particular conference, but actually using the Symposium UI to directly submit it to any conference that's allowing us to send talks in automatically.

Many, many precursors to this one. ~~First step is probably working with OpenCFP to get this feature enable-able for their conferences~~

Other considerations: Callback URL for acceptance/rejection? Which fields are sent? Do we need to add fields that are specifically about the sending-in (e.g. if a conference asks people to prioritize their talks or something else)

**Comment by mattstauffer** [comment]
This issue was moved to tightenco/symposium#29

**Comment by dhicking** [comment]
Given that OpenCFP is in maintenance mode, we're closing this.
