### ISSUE TITLE
Show talk page is narrower than necessary

### ISSUE THREAD

**Issue by mattstauffer** [tighten/symposium#296]
![image](https://user-images.githubusercontent.com/151829/111339469-2a4a1000-864e-11eb-9dd4-f4e4af57a2ae.png)

The left rail is a bunch of entries that are cutting across two lines, because it's so narrow, but it doesn't *need* to be this narrow.

Maybe we can widen the left rail on wider screens? We'd have to see if that screws up other pages... if it would, maybe the solution is to change the text of those version links to not be the full date?

**Comment by MarcyLina** [comment]
updated. I increased the width on the sidebar and it doesn't negatively affect any of the other pages

**Comment by mattstauffer** [comment]
🙌
