### ISSUE TITLE
Link text is too light

### ISSUE THREAD

**Issue by mattstauffer** [tighten/symposium#297]
![image](https://user-images.githubusercontent.com/151829/111339701-59f91800-864e-11eb-8b51-26246c56a229.png)

The nav link text needs to be darker.

Additionally, I think I'd like the label text on the forms to be darker than the link text; and maybe bold? it's a bit weird with it being the exact same color as the links.

**Comment by MarcyLina** [comment]
all text interactions that were `text-indigo-500 hover:text-800` have been reversed
