### ISSUE TITLE
Tweak OAuth page

### ISSUE THREAD

**Issue by mattstauffer** [tighten/symposium#299]
![image](https://user-images.githubusercontent.com/151829/111339946-8dd43d80-864e-11eb-871d-6c5f679d4a9b.png)

Should say "You don't have any Clients" yet with an s.
Drop the ! after "You don't have any Authorized Clients Yet"

Also, "Oops" is a weird title there.

Also.. this page doesn't actually work? Lol.. i tried to create a new personal token and it did nothing.

![image](https://user-images.githubusercontent.com/151829/111340132-bbb98200-864e-11eb-8c08-0eb3ba6518a9.png)
![image](https://user-images.githubusercontent.com/151829/111340332-e73c6c80-864e-11eb-9535-59b6b22006e9.png)

**Comment by andrewmile** [comment]
Closing as this issue has already been addressed.
