### ISSUE TITLE
Bug - cannot make talk public

### ISSUE THREAD

**Issue by asgrim** [tighten/symposium#357]
```
Given I have an existing talk that is not public
When I change the "Show on public speaker profile?" question to "Yes" and save my changes
Then I should see the talk on my public profile
```

Actual behaviour: the talk is not shown. When I go back to edit again, it shows "No" is selected.

Additionally, if I edit an existing talk that is currently on my public profile, even if I ensure "Yes" is selected, it gets removed.

I can see the value in `POST` for that field is `1` if that's any help:

![Screenshot from 2022-01-27 09-33-19](https://user-images.githubusercontent.com/496145/151331818-3395e2a4-47ab-4eec-9a7b-59093092bb35.png)

**Comment by mattstauffer** [comment]
@asgrim Thanks for reporting this bug! Hoping I can take a look and get a fix today. 🤞🏻

**Comment by mattstauffer** [comment]
@asgrim I just pushed code that should fix this issue. Would you mind taking a look?

**Comment by asgrim** [comment]
> @asgrim I just pushed code that should fix this issue. Would you mind taking a look?

I can confirm the issue is fixed, thank you @mattstauffer :pray:
