### ISSUE TITLE
[Proposal] - Peer Review Process

### ISSUE THREAD

**Issue by rtablada** [tighten/symposium#50]
*\* I hit submit too early... **

This is a fairly large set of features but could be really interesting for Symposium IMO and would be really useful and would replace Gists for my proposals (which I see as a bad alternative due to not really being able to lock things down).

First the User Stories:
- User can invite reviewer by email (maybe add a note?)
- Reviewer receives email to review proposal with link (logic tree here)
  - If email address is already registered then link to review screen
  - If email is not registered then link to subscribe screen
- Reviewer can view current and existing versions
- Reviewer can comment on proposal (not sure if this should be a stream that exists across all versions)
- Proposal creator can mark comment as addressed?

---

Like I said, it's alot and a rather big change.
I have been working on a lot of stuff with Lock for Access Controll using Conditions to do advanced permissions without resorting to database based permissions (which get out of sync too easily IMO).
One advantage on my recent projects has been that it has been that they were JS rendered so some of the super stateful UI things required by ACL things like this are really well suited and I haven't tackled these more stateful views on the server side.

Or if it's under a `reviews` uri then you don't have to worry quite as much, but you loose the sharability having the same URL between everyone.

**Comment by mattstauffer** [comment]
I think this is a great idea.

I'd trim it down to an MVP, which is:

Allow for sharing a version for review, with access only to the latest revision;
email is sent out with a share link that's unique to this version-sharee pair;
shares must register for an account in order to leave comments;
comments can be left, for now, only on the revision itself, not on a specific spot in the revision;
sharer gets email notified of comments.

Thoughts on that as a simpler MVP @rtablada ? @adamwathan ?

**Comment by adamwathan** [comment]
Yeah that sounds cool to me, one question would be is it important that each reviewee is commenting in isolation? Or is it more valuable to allow discussion between the people reviewing?

Is the reason for isolation...

1. I want to make sure people are giving me feedback based on their own thoughts, and not making comments based on things they didn't notice until reading someone else's comments.
2. I want to protect my reviewee's privacy (which could mean...)
    a. I have two reviewer's who don't get along and it would be awkward for them to be commenting in the same chain
    b. Some of the people I've asked to review are shy and won't feel comfortable sharing their criticisms in a place where others can see them.

All of that stuff affects what you'd wanna build to solve the problem in the best possible way.

On top of that, it's important to understand what problem reviews are solving too. It could be a lot of things...

1. _When I've put together a version of my abstract, I want to make sure others think it sounds like something they want to go to, so I know my talk will be worth doing._
2. _When I'm working on my abstract, I want to make sure my language and grammar is clear so the people reviewing the proposals will trust that I'm professional and will do a good job._
3. _When I'm working on my abstract, I want to know how it compares to what an experienced and successful speaker would've written for the same topic, so I can increase the chances of my abstract being accepted by the conference._

**Comment by adamwathan** [comment]
To expand a bit on the three potential problems I listed at the bottom...

The first one might be best solved by implementing some sort of anonymous voting system instead of peer review.

The second one might be best solved by letting people submit corrections like pull requests.

The third might be best solved by building something that connects to a HelpMeAbstract API and gets your proposals in front of experienced speakers instead of just your friends.

A general comment system per revision might be an option for solving these problems as well, but it's probably not the best solution for each problem. So let's just make sure we're solving problems, not building features :blush:

**Comment by mattstauffer** [comment]
Adam, can you just approach every feature request on every project I'm ever
on with this " So let's just make sure we're solving problems, not building
features [image: :blush:]" thing? It makes my brain work so much
differently <3

On Mon, May 11, 2015 at 2:19 PM, Adam Wathan <notifications@github.com>
wrote:

> To expand a bit on the three potential problems I listed at the bottom...
>
> The first one might be best solved by implementing some sort of anonymous
> voting system instead of peer review.
>
> The second one might be best solved by letting people submit corrections
> like pull requests.
>
> The third might be best solved by building something that connects to a
> HelpMeAbstract API and gets your proposals in front of experienced speakers
> instead of just your friends.
>
> A general comment system per revision might be an option for solving these
> problems as well, but it's probably not the best solution for each problem.
> So let's just make sure we're solving problems, not building features [image:
> :blush:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tightenco/symposium/issues/50#issuecomment-101004953>.
>



-- 

*Matt Stauffer*
*Partner + Technical Director*
Tighten Co.
352-682-2765

**Comment by rtablada** [comment]
I'm pretty booked this week, but do you guys want to set up a hangout some time to discuss more?

**Comment by adamwathan** [comment]
I'd totally be down :+1:

**Comment by mattstauffer** [comment]
Me too

Sent from Outlook




On Mon, May 11, 2015 at 11:58 AM -0700, "Adam Wathan" <notifications@github.com> wrote:












I'd totally be down

**Comment by elazar** [comment]
Integrating Symposium with helpmeabstract.com may address some of the concerns outlined here.

**Comment by mattstauffer** [comment]
@elazar Yah, I think that would be a great idea.
