### ISSUE TITLE
Do all users need to be able to create conferences?

### ISSUE THREAD

**Issue by adamwathan** [tighten/symposium#63]
Right now on the conferences page, we have an "Add Conference" button. I don't think there's any danger or anything in letting people add conferences, but let's make sure this solves a real problem for a speaker, just because it competes for attention in the interface.

Right now we're breaking things up in a very `Route::resource` sorta way, with a conferences index, talks index, etc. but I can imagine down the road improving this and reducing how much navigation people need to do to keep track of this stuff. Maybe the conference list is always in the sidebar for example so you're always reminded of what conferences are closing soon, or maybe we have a unified dashboard that has a call to action for adding a new talk, but also lists information about the conferences you're interested in.

Once you start to combine that information into something that gives a speaker the information they need in a really efficient way, it becomes much more important to trim any fat that's competing for attention in the interface.

Maybe a subtle "Are we missing a conference?" link in small text at the top right of the table that pops open the user's email client with a prefilled subject is a better solution than a whole conference CRUD interface for end users for example.

**Comment by adamwathan** [comment]
@besologic @dhicking @mattstauffer @dsheetz

**Comment by mattstauffer** [comment]
I've been wondering about that for a while--how do we handle inputting events? Letting just *anyone* do it feels sort of weird, but I don't know how to control.

I like the idea of a unified dashboard.

I don't liek the idea of conferences in the rail, unless it's just favorited conferences, just because I hope for us to have a LOT of conferences in the app.

The "Are we missing a conference?" button is AWESOME. I love it. Although I wouldn't be against keeping the form, but hiding it behind that button, and requiring someone to validate it or something? Just saves the pain of us having to manually enter it, etc.

**Comment by adamwathan** [comment]
Yeah I have no idea what a dashboard would look like but I do like the idea of thinking about what a user is logging into Symposium to do and building some sort of first page that makes it as easy as possible to do what they need and gives them the info they want to see as clearly as possible. All I'm sayin' is that that rarely lines up with standard separate CRUD pages for each resource, so just another thing we can figure out how to do better.

For inputting events, I mean we could do it in freakin' Sequel Pro in V1, not a big deal. But ultimately some sort of form would be great. Like click the "Don't see the conference you're looking for?" link or whatever and pop up a modal where they can fill out the basic fields, but just make everything optional and push it onto a queue of events to be approved by someone in the backend, where we can fill out missing details in the approval process. But a straight up email prompting us to go to the conference website and get the conference entered is probably a good MVP version.

**Comment by andrewmile** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change 'Add Conference' button to 'Suggest a Missing Conference'](https://trello.com/c/mGkmc00r/104-change-add-conference-button-to-suggest-a-missing-conference)

**Comment by mollybfisher** [comment]
**Clarification**: the current `add conference` submits the conference information. It does not automatically _create_ the new conference for all to view.

Manual submission –> sends details to the Slack channel –> that manual add can be added/managed by a Tighten team member.

Note Andrew's mention above of our new approach for now 😉
