### ISSUE TITLE
Build CFP Dashboard

### ISSUE THREAD

**Issue by mattstauffer** [tighten/symposium#65]
See #62 for the conversation that led to this.

![](https://cloud.githubusercontent.com/assets/4323180/7609173/39be443c-f93e-11e4-9c2e-ca1e800700b8.png)

This does _not_ include removing the current all conferences page. We will remove that once we've also replicated its functionality that isn't captured here (e.g. "ability to find a list of conferences I've submitted to that haven't happened yet")

**Comment by mattstauffer** [comment]
Note that we likely want a button somewhere at the bottom that says "Don't see your conference? Click here to suggest it" or something.

**Comment by mattstauffer** [comment]
branch: https://github.com/tightenco/symposium/tree/feature/cfp-dashboard

**Comment by rdohms** [comment]
I really like this.
